jubilee_stations = [
    "Stanmore",
    "Canons Park",
    "Queensbury",
    "Kingsbury",
    "Wembley Park",
    "Neasden",
    "Dollis Hill",
    "Willesden Green",
    "Kilburn",
    "West Hampstead",
    "Finchley Road",
    "Swiss Cottage",
    "St. John's Wood",
    "Baker Street",
    "Bond Street",
    "Green Park",
    "Westminster",
    "Waterloo",
    "Southwark",
    "London Bridge",
    "Bermondsey",
    "Canada Water",
    "Canary Wharf",
    "North Greenwich",
    "Canning Town",
    "West Ham",
    "Stratford",
]

elizabeth_line_stations = [
    "Reading",
    "Twyford",
    "Maidenhead",
    "Taplow",
    "Burnham",
    "Slough",
    "Langley",
    "Iver",
    "West Drayton",
    "Hayes & Harlington",
    "Southall",
    "Hanwell",
    "West Ealing",
    "Ealing Broadway",
    "Acton Main Line",
    "Paddington",
    "Bond Street",
    "Tottenham Court Road",
    "Farringdon",
    "Liverpool Street",
    "Whitechapel",
    "Canary Wharf",
    "Custom House",
    "Woolwich",
    "Abbey Wood",
    "Stratford",
    "Maryland",
    "Forest Gate",
    "Manor Park",
    "Ilford",
    "Seven Kings",
    "Goodmayes",
    "Chadwell Heath",
    "Romford",
    "Gidea Park",
    "Harold Wood",
    "Brentwood",
    "Shenfield",
]

final_cols = [
    "url",
    "id",
    "date_added",
    "title",
    "type",
    "available_all_week",
    "area",
    "postcode",
    "location",
    "nearest_station",
    "direct_line_to_office",
    "commute_to_office",
    "commute_to_central",
    "score",
    "average_price",
    "available",
    "minimum_term",
    "maximum_term",
    "bills_included?",
    "broadband_included",
    "furnishings",
    "garden/patio",
    "living_room",
    "balcony/roof_terrace",
    "#_flatmates",
    "total_#_rooms",
    "occupation",
    "gender",
    "min_age",
    "max_age",
    "room_1_bed_size",
    "room_1_price_pcm",
    "room_1_deposit",
    "room_2_bed_size",
    "room_2_price_pcm",
    "room_2_deposit",
    "room_3_bed_size",
    "room_3_price_pcm",
    "room_3_deposit",
    "room_4_bed_size",
    "room_4_price_pcm",
    "room_4_deposit",
    "image_url",
]

output_cols = [
    "url",
    "date_added",
    "type",
    "area",
    "score",
    "average_price",
    "commute_to_office",
    "commute_to_central",
    "direct_line_to_office",
    "location",
    "nearest_station",
    "available",
    "minimum_term",
    "maximum_term",
    "bills_included?",
    "broadband_included",
    "furnishings",
    "garden/patio",
    "living_room",
    "balcony/roof_terrace",
    "#_flatmates",
    "total_#_rooms",
    "gender",
]
