from dataclasses import dataclass
from datetime import datetime

@dataclass
class Room:
    url: str = None
    id: str = None
    date_added: datetime = datetime.today().date()
    title: str = None
    type: str = None
    available_all_week: bool = None
    area: str = None
    postcode: str = None
    location: str = None
    nearest_station: str = None
    direct_line_to_office: bool = None
    commute_to_office: str = None
    commute_to_central: str = None
    score: str = None
    average_price: str = None
    available: str = None
    minimum_term: str = None
    maximum_term: str = None
    bills_included: str = None
    broadband_included: str = None
    furnishings: str = None
    garden_or_patio: str = None
    living_room: str = None
    balcony_or_roof_terrace: str = None
    number_of_flatmates: int = None
    total_number_of_rooms: int = None
    occupation: str = None
    gender: str = None
    min_age: str = None
    max_age: str = None
    room_1_bed_size: str = None
    room_1_price_pcm: str = None
    room_1_deposit: str = None
    room_2_bed_size: str = None
    room_2_price_pcm: str = None
    room_2_deposit: str = None
    room_3_bed_size: str = None
    room_3_price_pcm: str = None
    room_3_deposit: str = None
    room_4_bed_size: str = None
    room_4_price_pcm: str = None
    room_4_deposit: str = None
    image_url: str = None